[package]
name = "rust-eth-key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = {version = "0.8.5", features = ["std"]}
secp256k1 = {version = "0.28.2", features = ["rand"]}
